### ISSUE TITLE
The system setting for the default language is not used

### ISSUE THREAD

**Issue by Gwnl** [atom/node-spellchecker#15]
On OSX the system preference in Keyboard/Text/Spelling is not used (with OSX 10.10.3 and the latest packages). I also tried with a clean ~/.atom directory but that didn't help.

This was originally reported in atom/spell-check#44 (not just for OSX but for Linux and Windows as well) but my guess is that the selection of dictionary is done upstream of the `spell-check` package.

**Comment by hollandjg** [comment]
This seems to be the root cause of https://github.com/atom/spell-check/issues/11 as well as https://github.com/atom/spell-check/issues/44

Could node-spellchecker implement an interface to the logic in the OS which selects a language based on a paragraph of text? For a mac, this would correspond to using the "Spelling: Automatic By Language" option which is present in the Keyboard>Text preference pane. 

This may require allowing the client to send each full paragraph to the relevant OS API, and would then return the misspelled words within that paragraph.

**Comment by hollandjg** [comment]
The default language is hard-coded as en_US in lib/spellchecker.js
```javascript
var ensureDefaultSpellCheck = function() {
  if (defaultSpellcheck) {
    return;
  }
  setDictionary('en_US', getDictionaryPath());
};
```
If a method for accessing the default dictionary is added to SpellcheckerImplementation class and used to replace the 'en_US' string here, that should solve this issue.

**Comment by hollandjg** [comment]
on Mac you don't even need to set the dictionary -- it's set by default. https://github.com/atom/node-spellchecker/pull/23 addresses this, but it needs checking on other platforms.

**Comment by paulcbetts** [comment]
You're looking at the legacy API, the vNext API which is also live supports arbitrary language dictionaries. It's up to Atom to implement this.
